disk_cache:
  enabled: true
download:
  icons: true
  multithreaded: true
gems: null
locale: null
memory_cache:
  data_expiration: 3600
  icon_expiration: 300
suggestions:
  by_type: 10
  enabled: true
system:
  notifications: true
  single_dependency_checking: false
ui:
  auto_scale: false
  hdpi: true
  style: null
  table:
    max_displayed: 50
  tray:
    default_icon: null
    updates_icon: null
updates:
  check_interval: 30
  pre_dependency_checking: true
  sort_packages: true
